### PR TITLE
Add many low-level cooking items

### PR DESCRIPTION
**Pull request by zajrik**
I just picked back up on my OSRS ironman that has barely any progress on it and I installed this plugin. I went to check my banked experience for cooking and was confused when it had nothing listed despite having shrimps and anchovies banked so I peaked at the code to find the available item set was missing quite a few early-game items. I'm sure I've missed some here but this should be a nice addition for now.

I didn't do too much digging so I wasn't sure if there was anything else that needed to be done to add supported items, so please let me know this isn't correct. I did check references in the project for some random `ExperienceItem` enum values to see if they were used anywhere else, indicating other places I would need to make changes but there were none so I'm pretty sure I'm safe, haha.

### CODE REVIEW

**Comment by TheStonedTurtle** [comment]
You will need to add an `Activity` for each new `ExperienceItem` that you've added for the plugin to calculate the experience properly.

If you had ran the test file you would have seen these new items in the grid but when selected there would be a "Unusable at current level" message displayed inside the modify panel as no activities were found.

**Comment by zajrik** [comment]
Ah, okay. Thank you for letting me know. I will look into this as soon as I can. There are errors when I open the project in VSCode so I'll give in and reinstall IntelliJ and go from there so I can actually run the tests and build the project.

**Comment by zajrik** [comment]
Okay, I've started working on the activities for all of the items I've added. I've got the project loaded up in IntelliJ and things are going smoothly. However, running the tests is not launching anything. Am I missing something? I'm pretty inexperienced when it comes to running/debugging Java projects. I'm only familiar with the language syntactically.

**Comment by zajrik** [comment]
I believe things are good to go now. I'm still unable to get anything to actually happen when I run the tests. IntelliJ just tells me `Test events were not received`. I'm not very familiar with IntelliJ at all. I haven't used a JetBrains editor in years now, so I don't know if I'm just doing something wrong or missing a step. Either way, please let me know if there's anything else I need to do at this point. 👍

**Comment by TheStonedTurtle** [comment]
You can follow the readme on the main plugin-hub repo, you probably need to buikd with gradle.

https://github.com/runelite/pluginhub

**Pull request merged**
