### PR TITLE
Calculate banked secondaries

### LINKED ISSUE #9: Support for banked secondaries for herblore
Howdy! One improvement I can think of is considering secondaries when calculating banked herblore experience, since your herb xp isn't truly banked unless you have the herbs _and_ the secondaries banked as well. Perhaps some way you could indicate a surplus of secondaries compared to herbs, or vice versa as well?

### PR DESCRIPTION
**Pull request by GregTheGreek**
Closes #9 

I haven't fully tested this yet, looking for initial feedback on the implementation.

Todo
- [x] Add option to config to allow toggle between high->low

### CODE REVIEW

**Comment by GregTheGreek** [comment]
@TheStonedTurtle Couldn't find info on runelite, how do you test locally?

**Comment by GregTheGreek** [comment]
@TheStonedTurtle 

Hey its ready for a review :)

**Comment by GregTheGreek** [comment]
@TheStonedTurtle Functionality is working with one hitch, I spent a bit of time trying to understand how updating works, but hit a couple roadblocks.

Right now I can only get this app to update on after increasing boosted stats

**Comment by GregTheGreek** [comment]
@TheStonedTurtle Any chance you can provide some feedback?

**Comment by TheStonedTurtle** [comment]
After looking at the UI I'm not sure if this is the way I'd like it implemented. Right now you just added a `Without Secondaries` line which is confusing, without secondaries what? Any activity requiring a secondary? Also, what if I want to see what level I will be and how far I am off from my next level when limited by banked secondaries? Right now that's all still based off the current calculations.


Also I didn't even look at your logic for finding missing experience but it's definitely wrong, I have have all the secondaries banked, I should be missing 0 experience 
image

**Comment by TheStonedTurtle** [comment]
I think the better way to handle this is to add a config option that changes the plugin into Secondary mode and then the entire calculator can account for that when displaying the info. The only thing we'd need to add is some UI that displays that they are in secondary mode, like a section displaying how many actions you couldn't do because of missing secondaries (similar to what the secondary grid does now, but in a way that shows you're missing out on this much XP because you can't do this many actions because you don't have this much of X resource)

That UI design is a big reason why I never attempted this

**Comment by TheStonedTurtle** [comment]
No changes made here in months, closing PR. Feel free to create a new one once the above has been addressed.

**Pull request closed without merging**
