### PR TITLE
Add secondary's name to tooltip 

### PR DESCRIPTION
**Pull request by lukaszklis**
Preview:

| Before | After |
| --- | --- |
| RuneLite_7AGs4PLadR | java_SazKiBAsKa |

### CODE REVIEW

**Comment by lukaszklis** [comment]
Ping ping :wave:

**Comment by TheStonedTurtle** [comment]
You can not call `itemManager.getItemComposition` unless you are on the client thread. If you enable exceptions by adding `-ea` to the VM options you will see this code is causing an AssertionError. I'm not sure how to easily accomplish what this PR set out to do.

Sorry for the delay on reviewing your PR, been busy with IRL stuff.

**Comment by lukaszklis** [comment]
Thanks for the review. I’ll double check the IDE setup to make sure I have all flags set. Thanks for taking the time, will update it once I get it to work. Happy holidays!

**Comment by lukaszklis** [comment]
Hey, after some investigation it is indeed impossible at this point to depend on the item composition. :( I’ll close the PR for now, whenever I have more ideas on how to get it to work, I will raise a new PR.

**Comment by TheStonedTurtle** [comment]
I've been able to work this feature into pr #39 in a round-about way. Took a while but we got there lol

**Comment by lukaszklis** [comment]
Wow! Thanks so much for dedicating your time!

**Pull request closed without merging**
