### PR TITLE
Add new prayer and cooking training methods to calc

### PR DESCRIPTION
**Pull request by 40Cakes**
Data from OSRS wiki:
https://oldschool.runescape.wiki/w/Blessed_bone_shards#Blessed_Bones
https://oldschool.runescape.wiki/w/Libation_bowl
https://oldschool.runescape.wiki/w/Jug_of_blessed_wine
https://oldschool.runescape.wiki/w/Jug_of_blessed_sunfire_wine
https://oldschool.runescape.wiki/w/Template:Meat

The [Zealot's robes](https://oldschool.runescape.wiki/w/Zealot%27s_robes) do have a chance to save sacrificed blessed bone shards, but still uses a 'charge' of the filled Libation bowl.

I assume Superior dragon bones require 70 prayer for this method as well, I am unable to verify this.

A blessed/sunfire wine (secondaries) can process 400 blessed bone shards.

### CODE REVIEW

**Comment by TheStonedTurtle** [comment]
Is this PR ready for review now?

**Comment by SeaifanAladdin** [comment]
Would it make more sense if each blessed bones can be broken down to bone shards, instead of exp directly? 
And then the jugs of wine or jugs of sunfire wine can act as a secondary for the bone shards?

I think we can also have Jug of Wine as an activity, with 2 sunfire splinters as a secondary, to create jug of sunfire wine.
I believe this suggestion would satisfy #144

**Comment by TheStonedTurtle** [comment]
> Would it make more sense if each blessed bones can be broken down to bone shards, instead of exp directly? And then the jugs of wine or jugs of sunfire wine can act as a secondary for the bone shards?
> 
> I think we can also have Jug of Wine as an activity, with 2 sunfire splinters as a secondary, to create jug of sunfire wine. I believe this suggestion would satisfy #144

Yeah definitely the best method would be to add a default Activity for each bone and then a `Convert to blessed` for each (that's applicable). The Blessed bones would then have an activity for converting to bone shards and using bone shards would have two activities, one for regular wine and one for blessed wine.

**Comment by 40Cakes** [comment]
Thanks for the tips, I've cleaned up the PR a bit. Forgive me for being a bit scuffed, I have never touched Java or a RuneLite plugin before, but I can't seem to get the sunfire wine secondaries with the spines to work..

- Simplified the activities down to produce bone shards, then choose the wine on the bone shards experience item
- Added Wyrmling activities for each method, factoring in the modifiers directly (Wyrmling bones are excluded from modifier `static final Set<Activity> BONES`)
- Zealot robes seems to apply to everything unless it's *excluded*, so I don't need to do anything here, right?

Would appreciate if anyone else could give it a test, I just finished up huge prayer grind on my iron (only account) and don't have a huge variety of bones at the moment to fully test every experience item.

**Comment by TheStonedTurtle** [comment]
I made some updates to this PR, but it now looks good to me. If there's any issues we can iteratively fix them as they pop up.

* Removed the ExperienceItem entries for the wines as there were not activities using them.
* Adjusted some of the Icons and Names for activities (personal preference)


I also fixed two bugs that existed prior to your PR:
47760096e4e89d2b4db28766d85620de35dc5c3a - Activities that use the same IconID as their output item and had an Output item that resulted in >1 item would only show this number if it was the only activity for the ExperienceItem. This fixes that so it now shows if there are multiple activites.
81b37fbaca0604ac8725cea2d7a8227d089252ee - Activities that required a secondary but did not have an output item were not being prepared properly so the name of the item would not show in the hover in the secondary grid. This fixes that.

**Pull request merged**
