### PR TITLE
Added secondaries supplies for Farming Tree

### PR DESCRIPTION
**Pull request by Jostavo**
I was kinda preparing for Farm 99 and wanted to know which tree secondaries I should collect and how many. I saw the plugin had no secondaries for tree farming and thought I could add them.

I think this should be enough. Any thoughts?

image

### CODE REVIEW

**Comment by Jostavo** [comment]
I'm really sorry if I'm bothering you, but do you think you can take a look at this PR soon? :D @TheStonedTurtle

**Comment by TheStonedTurtle** [comment]
My only problem with this is that the secondaries aren't actually required for the trees and I don't see any easy way to indicate that. I'm assuming most people would know that but 🤷

**Comment by Jostavo** [comment]
I guess there's a lot of 'relationship' between items, levels and requirements that would be a pain to represent. I thought of that but also thought it would be okay to implement like this

**Comment by Jostavo** [comment]
I could also implement some logic to recognize these stuff as 'Payment' or something like that

**Comment by Jostavo** [comment]
Considering Secondaries are related to activities, adding a 'payment' separately would increase the amount of parameters received and the changed code would be huge lol Just tried some stuff here locally

**Comment by TheStonedTurtle** [comment]
Easiest solution would be to duplicate all the activites and add a secondary for the new versions. This would add a dropdown to the sapling that allows the user to specify if they want the 1 with secondaries

**Comment by Jostavo** [comment]
I guess I can try it, but can you elaborate a bit more how exactly you think I can solve this? Sorry for the delay tho

**Comment by TheStonedTurtle** [comment]
You changed:
```java
WILLOW_SAPLING(ItemID.WILLOW_SAPLING, "Willow tree", 30, 1481.5,
		ExperienceItem.WILLOW_SAPLING, Secondaries.WILLOW_SAPLING, null),
```
to
```java
WILLOW_SAPLING(ItemID.WILLOW_SAPLING, "Willow tree", 30, 1481.5,
		ExperienceItem.WILLOW_SAPLING, Secondaries.WILLOW_SAPLING, null),
```

Instead of changing it add a new one that's named `WILLOW_SAPLING_PAID` directly under it.

**Comment by TheStonedTurtle** [comment]
No changes made here in over a year, closing the PR. Feel free to create a new one if you want

**Pull request closed without merging**
